config/routes.rb
Rails.application.routes.draw do
  root to: 'quizzes#show'
  patch '/finish', to: 'quizzes#finish', as: 'quiz_finish'
  patch '/start', to: 'quizzes#start', as: 'quiz_start'

  resources :questions, only: [] do
    post '/question_responses/:id/toggle', to: 'question_responses#toggle', as: 'response_toggle'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :question_responses, dependent: :destroy

  validates :text, presence: true

  def right?
    responses_count == right_responses_count
  end

  private

  def responses_count
    question_responses.count
  end

  def right_responses_count
    question_responses.select(&:right?).length
  end
end

app/models/question_response.rb
class QuestionResponse < ApplicationRecord
  belongs_to :question

  validates :text, presence: true

  def right?
    correct == checked
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions, dependent: :destroy

  validates :title, presence: true

  def right_answeres_number
    questions.select(&:right?).length
  end

  def questions_number
    questions.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/question_responses_controller.rb
class QuestionResponsesController < ApplicationController
  before_action :set_question_response, only: [:toggle]

  def toggle
    @question_response.update(checked: !@question_response.checked)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_response
      @question_response = QuestionResponse.find(params[:id])
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz

  def show
  end

  def finish
    if @quiz.update(finished: true)
      redirect_to :root
    else
      redirect_to :root, alert: 'Unable to finish the quiz.'
    end
  end

  def start
    if @quiz.update(finished: false)
      redirect_to :root
    else
      redirect_to :root, alert: 'Unable to start the quiz.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_responses_helper.rb
module QuestionResponsesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElopageQuiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question_responses/_question_response.html.erb
<tr>
  <label>
    <%= check_box_tag 'checked', question_response.id, question_response.checked,
        data: {
          remote: true,
          url: question_response_toggle_path(question_response.question, question_response),
          method: :post
        }
    %>
    <%= question_response.text %>
  </label>
</tr>

app/views/questions/_question.html.erb
<tr>
  <label>
    <%= question.text %>
    <table>
      <tbody>
        <%= render question.question_responses %>
      </tbody>
    </table>
  </label>
</tr>
<br>

app/views/quizzes/show.html.erb
<h1><%= @quiz.title %></h1>
<br>

<% if @quiz.finished? %>
  <h2>Your results</h2>

  <p>You got right <%= @quiz.right_answeres_number %> questions out of <%= @quiz.questions_number %></p>

  <%= button_to quiz_start_path(@quiz),
      method: :patch do %>
    Re-do the quiz
  <% end %>
<% else %>
  <table>
    <tbody>
      <%= render @quiz.questions %>
    </tbody>
  </table>

  <%= button_to quiz_finish_path(@quiz),
      method: :patch do %>
    Finish
  <% end %>
<% end %>